apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.quiz_time.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.quiz_time.service.type }}
  ports:
    - port: {{ .Values.quiz_time.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quiz-time.selectorLabels" . | nindent 4 }}
